# Generated by Django 4.2.1 on 2023-06-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(max_length=7),
        ),
    ]
